"""Gateway REQUEST interceptor.

The AgentCore Gateway calls this before every MCP request reaches a tool: initialize,
tools/list and tools/call. It hands back the request to send on, possibly changed, or
an answer of its own, which refuses the call. The Gateway may retry a call, so this
keeps no state and is safe to run twice.

Generated by AgentExpress from the templates checked on the Interceptors tab. Edit it
freely; generating it again from the tab replaces this file.

`event["mcp"]["gatewayRequest"]["headers"]` is there only with passRequestHeaders on.
The runtime then sends x-ax-session, x-ax-agent and x-ax-user with every call; the
Authorization header is the agent's own token, so never log the headers.
"""

import json
import logging

# >>> argumentGuard
import re

# <<< argumentGuard

logger = logging.getLogger()
logger.setLevel(logging.INFO)

VERSION = "1.0"

# What each checked template does, from the Interceptors tab.
# >>> settings
SETTINGS = json.loads(r"""
{
    "audit": {},
    "blockTools": {"tools": ["refunds___issueRefund"], "agents": []},
    "argumentGuard": {"denyPatterns": ["(?i)drop\\s+table"], "maxArgumentChars": 20000},
    "injectContext": {"arguments": {"runSession": "session"}},
    "custom": {}
}
""")
# <<< settings


def _run(event: dict) -> dict:
    """The run this call belongs to, from the x-ax-* headers ("" when not passed)."""
    headers = {str(k).lower(): v for k, v in
               (((event.get("mcp") or {}).get("gatewayRequest") or {}).get("headers") or {}).items()}
    return {"session": str(headers.get("x-ax-session") or ""), "agent": str(headers.get("x-ax-agent") or ""),
            "user": str(headers.get("x-ax-user") or "")}


def _tool_of(body: dict) -> str:
    """The tool a tools/call names ("<toolKey>___<toolName>"), else ""."""
    return str((body.get("params") or {}).get("name") or "") if body.get("method") == "tools/call" else ""


def _refuse(body: dict, reason: str) -> dict:
    """Answer the call here instead of the tool: the agent sees this error."""
    return {"interceptorOutputVersion": VERSION, "mcp": {"transformedGatewayResponse": {
        "statusCode": 200,
        "body": {"jsonrpc": "2.0", "id": body.get("id"),
                 "error": {"code": -32001, "message": f"Refused by interceptor: {reason}"}}}}}


# >>> audit
def audit(body: dict, run: dict, decision: str, reason: str = "") -> None:
    """One JSON line per request in CloudWatch Logs: what was called, by whom, and the
    decision. Argument NAMES only, never their values."""
    args = (body.get("params") or {}).get("arguments") if body.get("method") == "tools/call" else None
    logger.info(json.dumps({
        "interceptor": "request", "method": body.get("method"), "tool": _tool_of(body),
        "session": run["session"], "agent": run["agent"], "user": run["user"], "decision": decision,
        **({"reason": reason} if reason else {}),
        **({"arguments": sorted(args)} if isinstance(args, dict) else {}),
    }))
# <<< audit


# >>> blockTools
def _matches(name: str, patterns: list) -> bool:
    """"<toolKey>" matches every tool of that target; "<toolKey>___<toolName>" one tool."""
    n = name.lower()
    return any(n == str(p).lower() or n.startswith(f"{str(p).lower()}___") for p in patterns)


def block_tools(body: dict, run: dict) -> str | None:
    """Refuse a call to a listed tool: from the listed agents, or from any agent when none
    is listed. With agents listed and no x-ax-agent header, the call is refused."""
    s = SETTINGS.get("blockTools") or {}
    tool = _tool_of(body)
    if not tool or not _matches(tool, s.get("tools") or []):
        return None
    agents = s.get("agents") or []
    if not agents:
        return f"{tool} is blocked in this build"
    if not run["agent"]:
        return f"{tool} is blocked for some agents and this call does not say which agent made it"
    return f"{tool} is blocked for agent {run['agent']}" if run["agent"] in agents else None
# <<< blockTools


# >>> argumentGuard
_DENIED = [re.compile(p) for p in (SETTINGS.get("argumentGuard") or {}).get("denyPatterns") or []]


def argument_guard(body: dict, run: dict) -> str | None:
    """Refuse a tool call whose arguments are too long or match a denied pattern."""
    if body.get("method") != "tools/call":
        return None
    text = json.dumps((body.get("params") or {}).get("arguments") or {}, ensure_ascii=False, default=str)
    limit = int((SETTINGS.get("argumentGuard") or {}).get("maxArgumentChars") or 20000)
    if len(text) > limit:
        return f"its arguments are {len(text)} characters, over the limit of {limit}"
    for rx in _DENIED:
        if rx.search(text):
            return f"its arguments match a denied pattern ({rx.pattern})"
    return None
# <<< argumentGuard


# >>> injectContext
def inject_context(body: dict, run: dict) -> dict:
    """Set arguments from the run, overwriting whatever the model sent for them, so an
    agent cannot pass itself off as another session, agent or user."""
    if body.get("method") != "tools/call":
        return body
    params = body.setdefault("params", {})
    args = params.get("arguments") if isinstance(params.get("arguments"), dict) else {}
    for name, source in ((SETTINGS.get("injectContext") or {}).get("arguments") or {}).items():
        if run.get(source):
            args[name] = run[source]
        else:
            args.pop(name, None)
    params["arguments"] = args
    return body
# <<< injectContext


# >>> custom
def custom(body: dict, run: dict) -> str | None:
    """Your own check. Return a reason to refuse the call, or None to let it through;
    change `body` in place to change the request."""
    return None
# <<< custom


# The checks, in order: the first that gives a reason refuses the call.
CHECKS = [
    # >>> blockTools
    block_tools,
    # <<< blockTools
    # >>> argumentGuard
    argument_guard,
    # <<< argumentGuard
    # >>> custom
    custom,
    # <<< custom
]


def lambda_handler(event, context):
    body = ((event.get("mcp") or {}).get("gatewayRequest") or {}).get("body") or {}
    run = _run(event)
    for check in CHECKS:
        reason = check(body, run)
        if reason:
            # >>> audit
            audit(body, run, "refused", reason)
            # <<< audit
            return _refuse(body, reason)
    # >>> injectContext
    body = inject_context(body, run)
    # <<< injectContext
    # >>> audit
    audit(body, run, "allowed")
    # <<< audit
    return {"interceptorOutputVersion": VERSION, "mcp": {"transformedGatewayRequest": {"body": body}}}
