"""Gateway RESPONSE interceptor.

The AgentCore Gateway calls this after a tool answers and before the agent sees the
answer, for every MCP request: initialize, tools/list and tools/call. It hands back
the answer to deliver, possibly changed. The Gateway may retry a call, so this keeps
no state and is safe to run twice.

Generated by AgentExpress from the templates checked on the Interceptors tab. Edit it
freely; generating it again from the tab replaces this file.
"""

import json
import logging

# >>> redactPii
import re

# <<< redactPii

logger = logging.getLogger()
logger.setLevel(logging.INFO)

VERSION = "1.0"

# What each checked template does, from the Interceptors tab.
# >>> settings
SETTINGS = json.loads(r"""
{
    "audit": {},
    "redactPii": {"types": ["email", "phone", "ssn", "card"], "mask": "[REDACTED]"},
    "hideTools": {"tools": ["refunds___issueRefund"]},
    "capResult": {"maxChars": 20000},
    "custom": {}
}
""")
# <<< settings


def _strings(value, fn):
    """`value` with fn applied to every string in it, however deeply nested."""
    if isinstance(value, str):
        return fn(value)
    if isinstance(value, list):
        return [_strings(v, fn) for v in value]
    if isinstance(value, dict):
        return {k: _strings(v, fn) for k, v in value.items()}
    return value


def _tool_of(request: dict) -> str:
    return str((request.get("params") or {}).get("name") or "") if request.get("method") == "tools/call" else ""


# >>> audit
def audit(body: dict, request: dict) -> None:
    """One JSON line per answer in CloudWatch Logs: what was called, whether it failed,
    and how much came back. Never the content itself."""
    result = body.get("result")
    logger.info(json.dumps({
        "interceptor": "response", "method": request.get("method"), "tool": _tool_of(request),
        "error": bool(body.get("error")) or bool(isinstance(result, dict) and result.get("isError")),
        "resultChars": len(json.dumps(result, default=str)) if result is not None else 0,
    }))
# <<< audit


# >>> redactPii
_PII = {
    "card": re.compile(r"(?<!\d)\d(?:[ -]?\d){12,18}(?!\d)"),
    "ssn": re.compile(r"(?<!\d)\d{3}-\d{2}-\d{4}(?!\d)"),
    "phone": re.compile(r"(?<![\w+])(?:\+?\d{1,3}[ .-]?)?(?:\(\d{3}\)|\d{3})[ .-]?\d{3}[ .-]?\d{4}(?!\d)"),
    "email": re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}"),
}


def _luhn(text: str) -> bool:
    """A card number passes the Luhn check; most other long numbers do not."""
    digits = [int(c) for c in text if c.isdigit()][::-1]
    return sum(d if i % 2 == 0 else (d * 2 - 9 if d > 4 else d * 2) for i, d in enumerate(digits)) % 10 == 0


def redact_pii(body: dict, request: dict) -> dict:
    """Mask personal data in a tool's result. Patterns, so a backstop: a Bedrock
    guardrail is the managed check."""
    if request.get("method") != "tools/call" or "result" not in body:
        return body
    s = SETTINGS.get("redactPii") or {}
    kinds = [k for k in _PII if k in (s.get("types") or list(_PII))]
    mask = str(s.get("mask") or "[REDACTED]")

    def scrub(text: str) -> str:
        for kind in kinds:
            if kind == "card":
                text = _PII[kind].sub(lambda m: mask if _luhn(m.group(0)) else m.group(0), text)
            else:
                text = _PII[kind].sub(mask, text)
        return text

    body["result"] = _strings(body["result"], scrub)
    return body
# <<< redactPii


# >>> hideTools
def _matches(name: str, patterns: list) -> bool:
    """"<toolKey>" matches every tool of that target; "<toolKey>___<toolName>" one tool."""
    n = name.lower()
    return any(n == str(p).lower() or n.startswith(f"{str(p).lower()}___") for p in patterns)


def hide_tools(body: dict, request: dict) -> dict:
    """Leave listed tools out of tools/list, so no agent is offered them. A hidden tool
    can still be called by name: refuse it too (blockTools, or a Cedar forbid)."""
    result = body.get("result")
    listed = result.get("tools") if isinstance(result, dict) else None
    if request.get("method") != "tools/list" or not isinstance(listed, list):
        return body
    hidden = (SETTINGS.get("hideTools") or {}).get("tools") or []
    result["tools"] = [t for t in listed if not (isinstance(t, dict) and _matches(str(t.get("name") or ""), hidden))]
    return body
# <<< hideTools


# >>> capResult
def cap_result(body: dict, request: dict) -> dict:
    """Cut each text in a tool's result to at most maxChars, saying how much was cut."""
    result = body.get("result")
    if request.get("method") != "tools/call" or not isinstance(result, dict):
        return body
    limit = int((SETTINGS.get("capResult") or {}).get("maxChars") or 20000)
    for item in result.get("content") or []:
        text = item.get("text") if isinstance(item, dict) else None
        if isinstance(text, str) and len(text) > limit:
            item["text"] = (f"{text[:limit]}\n[{len(text) - limit} more characters cut by the Gateway's "
                            "response interceptor]")
    return body
# <<< capResult


# >>> custom
def custom(body: dict, request: dict) -> dict:
    """Your own change to the answer: return the body to deliver."""
    return body
# <<< custom


# The changes, in order, each given the previous one's body.
STEPS = [
    # >>> redactPii
    redact_pii,
    # <<< redactPii
    # >>> hideTools
    hide_tools,
    # <<< hideTools
    # >>> capResult
    cap_result,
    # <<< capResult
    # >>> custom
    custom,
    # <<< custom
]


def lambda_handler(event, context):
    mcp = event.get("mcp") or {}
    request = (mcp.get("gatewayRequest") or {}).get("body") or {}
    response = mcp.get("gatewayResponse") or {}
    body = response.get("body")
    if isinstance(body, dict):
        for step in STEPS:
            body = step(body, request)
        # >>> audit
        audit(body, request)
        # <<< audit
    out = {"body": body}
    # A streamed answer's later events carry no status: only the first one may set it.
    if "statusCode" in response:
        out["statusCode"] = response["statusCode"]
    return {"interceptorOutputVersion": VERSION, "mcp": {"transformedGatewayResponse": out}}
